django/daikuan/app/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import admin
from . import views
# from django.contrib.auth import views as auth_views
app_name='app'
urlpatterns = [
    url(r'^submit$',views.submit,name='submit'),
    url(r'^shouye$',views.shouye,name='shouye'),
    url(r'^index$', views.index,name='index'),
    url(r'^daikuaninfo$',views.daikuaninfo,name='daikuaninfo'),
    url(r'^alldaikuaninfo/(\d*)$',views.daikuaninfo2,name='daik2'),
    url(r'^stuinfo$',views.stuinfo,name='stuinfo'),
    url('^daikuanshenq$',views.daikuanshenq,name='daikuanshenq'),
    url(r'^login$', views.login,name='login'),
    url(r'^logout$', views.logout,name='logout'),
    url(r'^teainfo$',views.teainfo,name='teainfo'),
    url(r'^daikuanshenp/(\d*)$',views.daikuanshenp,name='daikuanshenp'),
    url(r'^upload$',views.upload,name='upload'),
    url(r'^change$',views.change,name='change'),
    url(r'^allstuinfo/(\d*)$',views.allinfo,name='allinfo'),
    url(r'^detail/([A-Z]{2}\d{6})$',views.detail,name='detail'),
    url(r'^shenh/(.*)$',views.shenh,name='shenh'),
    url(r'^daikuandetail/([A-Z]{2}\d{6})$',views.daikuandetail,name='dkdetail'),
    url(r'^tuihui/([A-Z]{2}\d{6})$',views.tuihui,name='tuihui'),
    url(r'^huankuan/([A-Z]{2}\d{6})$',views.huankuan,name='huankuan'),
    url(r'^daikuanshenq2$',views.daikuanshenq2,name='daikuanshenq2'),
    url(r'^addadm$',views.admm,name='addadm'),
    url(r'^deladm$',views.admm2,name='deladm'),
]

django/daikuan/daikuan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

]

django/daikuan/app/models.py
from django.db import models

# Create your models here.
class Stuinfo(models.Model):
    StuNum=models.CharField(max_length=8,primary_key=True,verbose_name='学号')
    StuName=models.CharField(max_length=20,verbose_name='姓名')
    Sex=models.CharField(max_length=2,choices=(('W','女'),('M','男')),verbose_name='性别')
    department=models.CharField(max_length=20,choices=(('L','理工部'),('W','文艺部'),('G','管理部'),('J','经济系')),verbose_name='系别')
    stuid=models.CharField(max_length=18,verbose_name='身份证')
    Tel=models.CharField(max_length=12,verbose_name='电话')
    major=models.CharField(verbose_name='专业',max_length=20)
    email=models.EmailField(verbose_name='邮箱',blank=True,help_text='可不填')
    def __str__(self):
        return self.StuNum
    class Meta:
        verbose_name='学生信息'
        verbose_name_plural='学生信息'

class Teacher(models.Model):
    TeaNum=models.CharField(max_length=8,primary_key=True,verbose_name='职工号')
    TeaName=models.CharField(max_length=20,verbose_name='姓名')
    Tel=models.CharField(max_length=12,verbose_name='电话')
    sex = models.CharField(max_length=2,choices=(('W', '女'), ('M', '男')), verbose_name='性别')
    def __str__(self):
        return self.TeaNum
    class Meta:
        verbose_name = '教师信息'
        verbose_name_plural = '教师信息'

class shenq(models.Model):
    # models=Stuinfo
    num = models.AutoField(primary_key=True,verbose_name='预编码号')
    Stunum=models.ForeignKey(Stuinfo,on_delete=models.CASCADE,verbose_name='学号')
    time=models.DateTimeField(verbose_name='申请时间',auto_now=True)
    edu = models.IntegerField(default=10000, verbose_name='贷款额度')
    status=models.IntegerField(default=0,verbose_name='审批状态')
    def __str__(self):
        return str(self.num)
    class Meta:
        verbose_name = '贷款申请信息'
        verbose_name_plural = '贷款申请信息'

class daikuan(models.Model):
    num=models.OneToOneField(shenq,verbose_name='预编码号',on_delete=models.CASCADE)
    id=models.AutoField(primary_key=True,verbose_name='编码号')
    TeaNum=models.ForeignKey(Teacher,on_delete=models.CASCADE,verbose_name='职工号')
    time=models.DateTimeField(verbose_name='审批时间',auto_now=True)
    status = models.IntegerField(default=0, verbose_name='还款状态')
    need = models.IntegerField(default=0,verbose_name='所需还款')
    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name = '贷款信息'
        verbose_name_plural = '贷款信息'


class Register(models.Model):
   username = models.CharField(max_length = 32,verbose_name = '学号',)
   password = models.CharField(max_length = 32,verbose_name = '密码',default='jianghuai')
   name=models.CharField(max_length=20,verbose_name='姓名',default='')
   email = models.EmailField(verbose_name = '注册邮箱',blank=True,help_text='可不填')
   phone_number = models.CharField(max_length = 14,verbose_name = '电话号码',blank=True)
   class Meta:
       verbose_name_plural='账号管理'
       verbose_name='账号管理'

django/daikuan/app/templates/app/teacher/adminchange.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}新增账号{% endblock %}
{% block detail %}
    <div class="caidan right">
         <form id="register" action="" method="post" >
             {% csrf_token %}
            <table class="table">
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">专业</td><td colspan="2"><input    name="major" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入专业拼音首字母大写" required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">院系</td><td colspan="2"><input    name="yx" type="number" style="line-height: 25px;border: none;outline:none" placeholder="院系数字代号" ></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">入学年份</td><td colspan="2"><input   id='time' name="year" type="text" style="line-height: 25px;border: none;outline:none" placeholder='年份' required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">班级人数</td><td colspan="2"><input    name="pn" type="number" style="line-height: 25px;border: none;outline:none" placeholder="该专业新生人数" ></td></tr>
            </tbody>
        </table>
        <button class="btn btn-success" type="submit" style="margin: 0 20% 0 20%;width: 60%" οnclick="registerid_submit()">提交</button>
         </form>
    </div>
{% endblock %}

django/daikuan/app/templates/app/teacher/allinfo.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}学生信息{% endblock %}
{% block detail %}
    <h1 style="text-align: center">所有学生个人信息如下</h1>
    <div class="caidan right">

        <table class="stuinfo">
                <tr><th>学号</th><th>姓名</th><th>性别</th><th>院系</th><th>专业</th></tr>
            {% for i in page %}
                <tr><td>{{ i.StuNum }}</td><td>{{ i.StuName }}</td><td>{{ i.get_Sex_display }}</td><td>{{ i.get_department_display }}</td><td>{{ i.major }}</td></tr>
            {% endfor %}
        </table>

        <div class="page">
            {% if page.has_previous %}
                <a href="{% url 'app:allinfo' page.previous_page_number %}">上一页</a>
            {% endif %}
                <span class="current">第{{ page.number }}页/共{{ page.paginator.num_pages }}页 </span>
            {% if page.has_next %}
                <a href="{% url 'app:allinfo' page.next_page_number %}">下一页</a>
            {% endif %}

        </div>
    </div>
{% endblock %}

django/daikuan/app/templates/app/teacher/daikuanshenp.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}待审批{% endblock %}
{% block detail %}
    <h1 style="text-align: center">待审批信息如下</h1>
    <div class="caidan right">
    <table class="stuinfo">
            <tr><th>学号</th><th>申请时间</th><th>额度</th><th>审批链接</th></tr>
        {% for i in page %}
            <tr><td>{{ i.Stunum_id}}</td><td>{{ i.time }}</td><td>{{ i.edu }}</td><td><a class="nosolid" href="{% url 'app:detail' i.Stunum_id %}" >审批</a></td></tr>
        {% endfor %}
    </table>
    <div class="page">
        {% if page.has_previous %}
            <a href="{% url 'app:allinfo' page.previous_page_number %}">上一页</a>
        {% endif %}
            <span class="current">第{{ page.number }}页/共{{ page.paginator.num_pages }}页 </span>
        {% if page.has_next %}
            <a href="{% url 'app:allinfo' page.next_page_number %}">下一页</a>
        {% endif %}

    </div>
    </div>
{% endblock %}

django/daikuan/app/templates/app/teacher/detail.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}待审批{% endblock %}
{% block detail %}
    <div class="caidan right">
         <form id="register" action="{% url 'app:shenh' stu.StuNum %}" method="post" >
            <table class="table">
                {% csrf_token %}
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生姓名</td><td colspan="2"><output    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none"  ></output>{{ stu.StuName }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生学号</td><td colspan="2"><output    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none"  ></output>{{ stu.StuNum }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生院系</td><td colspan="2"><output    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none"  ></output>{{ stu.get_department_display }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生专业</td><td colspan="2"><output    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none"  ></output>{{ stu.major }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">申请时间</td><td colspan="2"><output    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none"  ></output>{{ daikuan.time }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生性别</td><td colspan="2"><output    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none"  ></output>{{ stu.get_Sex_display }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">预编码号</td><td colspan="2"><input    name="num" type="text" style="line-height: 25px;border: none;outline:none"  required value="{{ daikuan.num}}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">您的职工号</td><td colspan="2"><input    name="TeaNum" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入职工号号" required value="{{ tea.TeaNum }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">额度</td><td ><output   name="edu" style="line-height: 25px;border: none;outline:none" type="tel" minlength="11" maxlength="11"  ></output>{{ daikuan.edu }}</td></tr>
            </tbody>
        </table>

        <button class="btn btn-success" type="submit" style="margin: 0 30% 0 30%;width: 30%">审核通过</button>
         </form>
         <form action="{% url 'app:tuihui' stu.StuNum %}">
             <button class="btn btn-success" type="submit" style="float: left;margin: 10px 30% 0 30%;width: 30%" >审核退回</button>
         </form>

{% endblock %}</div>

django/daikuan/app/templates/app/teacher/detail2.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}待审批{% endblock %}
{% block detail %}
    <div class="caidan right">
    <h1>学号为{{ daik.num.Stunum.StuNum }}的同学贷款信息如下</h1>
            <table class="table">
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生姓名</td><td colspan="2"><output    name="TeaName"  style="line-height: 25px;border: none;outline:none"  ></output>{{ daik.num.Stunum.StuName }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生学号</td><td colspan="2"><output    name="TeaName"  style="line-height: 25px;border: none;outline:none"  ></output>{{ daik.num.Stunum }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生院系</td><td colspan="2"><output    name="TeaName"  style="line-height: 25px;border: none;outline:none"  ></output>{{ daik.num.Stunum.get_department_display }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生专业</td><td colspan="2"><output    name="TeaName"  style="line-height: 25px;border: none;outline:none"  ></output>{{ daik.num.Stunum.major }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学生性别</td><td colspan="2"><output    name="TeaName"  style="line-height: 25px;border: none;outline:none"  ></output>{{ daik.num.Stunum.get_Sex_display }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">预编码号</td><td colspan="2"><output    name="num"  style="line-height: 25px;border: none;outline:none"  >{{ daik.num.num}}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">审批人职工号</td><td colspan="2"><output    name="TeaNum"  style="line-height: 25px;border: none;outline:none"  >{{ daik.TeaNum.TeaNum }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">审批人姓名</td><td ><output   name="edu" style="line-height: 25px;border: none;outline:none"    ></output>{{ daik.TeaNum.TeaName }}</td></tr>                 
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">申请时间</td><td colspan="2"><output    name="TeaName"  style="line-height: 25px;border: none;outline:none"  ></output>{{ daik.num.time }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">额度</td><td ><output   name="edu" style="line-height: 25px;border: none;outline:none"    ></output>{{ daik.num.edu }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">审批时间</td><td ><output   name="edu" style="line-height: 25px;border: none;outline:none"    ></output>{{ daik.time }}</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">应还贷款</td><td ><output   name="edu" style="line-height: 25px;border: none;outline:none"    ></output>
                {% if daik.need %}
                    {{ daik.need }}
                {% else %}
                    <p id="moneyneed"></p>
                {% endif %}
                </td></tr>
            </tbody>
        </table>

    <form action="{% url 'app:huankuan' daik.num.Stunum %}" method="post">
    {% csrf_token %}
        <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">还款金额</td><td ><input    name="money" type="number" style="line-height: 25px;border: none;outline:none" placeholder="不输入默认全还" ></td></tr>
        <button >确定还款</button>
    </form>

<script>
    date= new Date()
    oldyear={{ daik.time.year }}
    year=date.getFullYear()
    oldmonth={{ daik.time.month }}
    Month=date.getMonth()+1
    money=((year-oldyear)*12+Month-oldmonth)*{{ daik.num.edu }}*0.05+{{ daik.num.edu }};
    document.getElementById('moneyneed').innerHTML=money</script>
{% endblock %}</div>

django/daikuan/app/templates/app/teacher/teainfo.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}教师信息{% endblock %}
{% block detail %}
    <h1 style="text-align: center">您的个人信息如下</h1>
    <div class="caidan right">
         <form id="register" action="{% url 'app:change' %}" method="post" >
            <table class="table">
                {% csrf_token %}
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">真实姓名</td><td colspan="2"><input    name="TeaName" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入您的名字" required value="{{ tea.TeaName }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">职工号</td><td colspan="2"><input    name="TeaNum" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入职工号号" required value="{{ tea.TeaNum }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">性别</td><td colspan="2"><input class="myforms-3-2" type="text" style="line-height: 25px;border: none;outline:none" checked ="checked" name="Sex" value="{{ tea.get_sex_display }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">联系方式</td><td ><input   name="Tel" style="line-height: 25px;border: none;outline:none" type="tel" minlength="11" maxlength="11" placeholder="请输入手机" required value="{{ tea.Tel }}"></td></tr>
            </tbody>
        </table>
        <button class="btn btn-success" type="submit" style="margin: 0 20% 0 20%;width: 60%" οnclick="registerid_submit()">修改</button>
         </form>
    </div>
{% endblock %}