django/daikuan/app/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import admin
from . import views
# from django.contrib.auth import views as auth_views
app_name='app'
urlpatterns = [
    url(r'^submit$',views.submit,name='submit'),
    url(r'^shouye$',views.shouye,name='shouye'),
    url(r'^index$', views.index,name='index'),
    url(r'^daikuaninfo$',views.daikuaninfo,name='daikuaninfo'),
    url(r'^alldaikuaninfo/(\d*)$',views.daikuaninfo2,name='daik2'),
    url(r'^stuinfo$',views.stuinfo,name='stuinfo'),
    url('^daikuanshenq$',views.daikuanshenq,name='daikuanshenq'),
    url(r'^login$', views.login,name='login'),
    url(r'^logout$', views.logout,name='logout'),
    url(r'^teainfo$',views.teainfo,name='teainfo'),
    url(r'^daikuanshenp/(\d*)$',views.daikuanshenp,name='daikuanshenp'),
    url(r'^upload$',views.upload,name='upload'),
    url(r'^change$',views.change,name='change'),
    url(r'^allstuinfo/(\d*)$',views.allinfo,name='allinfo'),
    url(r'^detail/([A-Z]{2}\d{6})$',views.detail,name='detail'),
    url(r'^shenh/(.*)$',views.shenh,name='shenh'),
    url(r'^daikuandetail/([A-Z]{2}\d{6})$',views.daikuandetail,name='dkdetail'),
    url(r'^tuihui/([A-Z]{2}\d{6})$',views.tuihui,name='tuihui'),
    url(r'^huankuan/([A-Z]{2}\d{6})$',views.huankuan,name='huankuan'),
    url(r'^daikuanshenq2$',views.daikuanshenq2,name='daikuanshenq2'),
    url(r'^addadm$',views.admm,name='addadm'),
    url(r'^deladm$',views.admm2,name='deladm'),
]

django/daikuan/daikuan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

]

django/daikuan/app/templates/app/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{#  标题#}
    <title>
        {% block title %}
            江淮助学贷款系统首页
        {% endblock %}
    </title>
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
{#  子页面加格式#}
    {% block css %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mysite</a>
        </div>
          <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'app:shouye' %}">主页</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
{#            导航栏上会改变的信息#}
              {% block xinxi %}
                    <li><a href="http://127.0.0.1:8000/admin">管理员登录</a></li>
                    <li><a href="{% url 'app:login' %}">老师登录</a></li>
                    <li><a href="{% url 'app:login' %}">学生登录</a></li>
              {% endblock %}

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
{#    具体内容的添加#}
    {% block content %} {% endblock %}
{#    添加图片放这里#}
    {% block image %}{% endblock %}
    <script src="{% static 'JS/jquery-3.4.1.js' %}"></script>
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

django/daikuan/app/templates/app/base/base_stu.html
{% extends 'app/base/base.html' %}
{% load staticfiles %}
{% block xinxi %}
    {% if stu %}
        <li><a>欢迎{{ stu.StuName }}同学</a></li><li><a href="{% url 'app:logout' %}">注销</a></li>
    {% else %}
        <li><a>欢迎{{ name.name }}同学</a></li><li><a href="{% url 'app:logout' %}">注销</a></li>
    {%  endif %}
{% endblock %}
{% block css %}
    <script>
    var canvas,context,snows=[]
    class Snow{
                constructor(x,radis,speed,color){
                    this.x=x;
                    this.y=0;
                    this.radis=radis;
                    this.speed=speed;
                    this.color=color
                }
                draw(context){
                    context.save()
                    context.translate(this.x,this.y)
                    context.fillStyle=this.color
                    context.beginPath()
                    context.arc(0,0,this.radis,0,2*Math.PI,true)
                    context.closePath()
                    context.fill()
                    context.restore()
                }
            }
            function createSnow() {
                if(snows.length<1000){
                    let x=Math.random()*canvas.width+1
                    let radis=Math.random()*3+1
                    let speed=Math.random()*3+1
                    let color='white'
                    let snow=new Snow(x,radis,speed,color)
                    snows.push(snow)
                }
            }
            function snowMove(snow,index) {
                snow.y+=snow.speed;
                if(snow.y>canvas.height){
                    snows.splice(index,1)
                }else{
                    snow.draw(context)
                }
            }
            function init() {
                requestAnimationFrame(init);
                let back_img=new Image()
                back_img.src='https://s2.ax1x.com/2019/05/25/VAY1nf.jpg'
                context.clearRect(0,0,canvas.width,canvas.height);
                context.drawImage(back_img,0,0,canvas.width,canvas.height);
                createSnow();
                snows.forEach(snowMove)
            }
        window.onload=function () {
            canvas=document.getElementById('snow');
            context=canvas.getContext('2d');
            init()
        }
    </script>
    <style>
        body{
            position: relative;
        }
        #game{
            position: absolute;
            top: 50%;
            right: 50%;
            transform: translate(-50%,-50%);
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/base2.css' %}">
{% endblock %}
{% block title %}江淮助学贷款系统{% endblock %}
{% block content %}
    <div class="caidan left">
    <div class="menu">
        信息查询
       <li class="zicaidan"><a href="{% url 'app:stuinfo' %}">学生信息</a></li>
        <li class="zicaidan"><a href="{% url 'app:daikuaninfo' %}">贷款信息</a></li>
    </div>
    <div class="menu">
        申请
       <li class="zicaidan"><a href="{% url 'app:daikuanshenq' %}">贷款申请</a></li>
    </div>
    </div>
    {% if error_msg %}
    <a href="{% url 'app:upload' %}"><font color="red" >{{ error_msg }}</font></a>
    {%  endif %}
    {% if erro_msg %}
    <a href="{% url 'app:daikuanshenq' %}"><font color="red" >{{ erro_msg }}</font></a>
    {%  endif %}
    {% if mes %}
        <a href="{% url 'app:daikuaninfo' %}"><font color="red" >{{ mes }}</font></a>
    {% endif %}
    {%  if mes2 %}
        <a href="{%  url 'app:daikuanshenq2' %}"><font color="red" >{{ mes2}}</font></a>
    {%  endif %}
    {%  if err %}
        <font color="red" style="position: absolute; top: 0;left: 0">{{ err }}</font>
    {%  endif %}
    {% block detail %} <canvas id="snow" style="width: 80%;height: 100%"> </canvas>{% endblock %}
{%  endblock %}

django/daikuan/app/templates/app/base/base_tea.html
{% extends 'app/base/base.html' %}
{% load staticfiles %}
{% block xinxi %}
<li><a>欢迎{{ tea.TeaName }}老师</a></li>
    <li><a href="{% url 'app:logout' %}">注销</a></li>
{% endblock %}
{% block css %}
        <script>
    var canvas,context,snows=[]
    class Snow{
                constructor(x,radis,speed,color){
                    this.x=x;
                    this.y=0;
                    this.radis=radis;
                    this.speed=speed;
                    this.color=color
                }
                draw(context){
                    context.save()
                    context.translate(this.x,this.y)
                    context.fillStyle=this.color
                    context.beginPath()
                    context.arc(0,0,this.radis,0,2*Math.PI,true)
                    context.closePath()
                    context.fill()
                    context.restore()
                }
            }
            function createSnow() {
                if(snows.length<1000){
                    let x=Math.random()*canvas.width+1
                    let radis=Math.random()*3+1
                    let speed=Math.random()*3+1
                    let color='white'
                    let snow=new Snow(x,radis,speed,color)
                    snows.push(snow)
                }
            }
            function snowMove(snow,index) {
                snow.y+=snow.speed;
                if(snow.y>canvas.height){
                    snows.splice(index,1)
                }else{
                    snow.draw(context)
                }
            }
            function init() {
                requestAnimationFrame(init);
                let back_img=new Image()
                back_img.src='https://s2.ax1x.com/2019/05/25/VAY1nf.jpg'
                context.clearRect(0,0,canvas.width,canvas.height);
                context.drawImage(back_img,0,0,canvas.width,canvas.height);
                createSnow();
                snows.forEach(snowMove)
            }
        window.onload=function () {
            canvas=document.getElementById('snow');
            context=canvas.getContext('2d');
            init()
        }
    </script>
    <style>
        body{
            position: relative;
        }
        #game{
            position: absolute;
            top: 50%;
            right: 50%;
            transform: translate(-50%,-50%);
        }
    </style>
    <link rel="stylesheet" href="{% static 'css/base2.css' %}">
{% endblock %}
{% block title %}江淮贷款系统{% endblock %}
{% block content %}
    <div class="caidan left">
    <div class="menu">
        信息查询
       <li class="zicaidan"><a href="{% url 'app:allinfo' 1 %}">学生信息</a></li>
        <li class="zicaidan"><a href="{% url 'app:daik2' 1 %}">贷款信息</a></li>
        <li class="zicaidan"><a href="{% url 'app:teainfo' %}">个人信息</a></li>
    </div>
    <div class="menu">
        审批
       <li class="zicaidan"><a href="{% url 'app:daikuanshenp' 1 %}">贷款审批</a></li>
    </div>
     <div class="menu">
        账号管理
       <li class="zicaidan"><a href="{% url 'app:addadm'  %}">新建账号</a></li>
       <li class="zicaidan"><a href="{% url 'app:deladm'  %}">删除账号</a></li>
    </div>
    </div>
    <span style="color:red;">{{ error }}</span>
    {% block detail %}
        <canvas id="snow" style="width: 80%;height: 100%">
    {% endblock %}
{%  endblock %}