django/daikuan/app/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import admin
from . import views
# from django.contrib.auth import views as auth_views
app_name='app'
urlpatterns = [
    url(r'^submit$',views.submit,name='submit'),
    url(r'^shouye$',views.shouye,name='shouye'),
    url(r'^index$', views.index,name='index'),
    url(r'^daikuaninfo$',views.daikuaninfo,name='daikuaninfo'),
    url(r'^alldaikuaninfo/(\d*)$',views.daikuaninfo2,name='daik2'),
    url(r'^stuinfo$',views.stuinfo,name='stuinfo'),
    url('^daikuanshenq$',views.daikuanshenq,name='daikuanshenq'),
    url(r'^login$', views.login,name='login'),
    url(r'^logout$', views.logout,name='logout'),
    url(r'^teainfo$',views.teainfo,name='teainfo'),
    url(r'^daikuanshenp/(\d*)$',views.daikuanshenp,name='daikuanshenp'),
    url(r'^upload$',views.upload,name='upload'),
    url(r'^change$',views.change,name='change'),
    url(r'^allstuinfo/(\d*)$',views.allinfo,name='allinfo'),
    url(r'^detail/([A-Z]{2}\d{6})$',views.detail,name='detail'),
    url(r'^shenh/(.*)$',views.shenh,name='shenh'),
    url(r'^daikuandetail/([A-Z]{2}\d{6})$',views.daikuandetail,name='dkdetail'),
    url(r'^tuihui/([A-Z]{2}\d{6})$',views.tuihui,name='tuihui'),
    url(r'^huankuan/([A-Z]{2}\d{6})$',views.huankuan,name='huankuan'),
    url(r'^daikuanshenq2$',views.daikuanshenq2,name='daikuanshenq2'),
    url(r'^addadm$',views.admm,name='addadm'),
    url(r'^deladm$',views.admm2,name='deladm'),
]

django/daikuan/daikuan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

]

django/daikuan/app/models.py
from django.db import models

# Create your models here.
class Stuinfo(models.Model):
    StuNum=models.CharField(max_length=8,primary_key=True,verbose_name='学号')
    StuName=models.CharField(max_length=20,verbose_name='姓名')
    Sex=models.CharField(max_length=2,choices=(('W','女'),('M','男')),verbose_name='性别')
    department=models.CharField(max_length=20,choices=(('L','理工部'),('W','文艺部'),('G','管理部'),('J','经济系')),verbose_name='系别')
    stuid=models.CharField(max_length=18,verbose_name='身份证')
    Tel=models.CharField(max_length=12,verbose_name='电话')
    major=models.CharField(verbose_name='专业',max_length=20)
    email=models.EmailField(verbose_name='邮箱',blank=True,help_text='可不填')
    def __str__(self):
        return self.StuNum
    class Meta:
        verbose_name='学生信息'
        verbose_name_plural='学生信息'

class Teacher(models.Model):
    TeaNum=models.CharField(max_length=8,primary_key=True,verbose_name='职工号')
    TeaName=models.CharField(max_length=20,verbose_name='姓名')
    Tel=models.CharField(max_length=12,verbose_name='电话')
    sex = models.CharField(max_length=2,choices=(('W', '女'), ('M', '男')), verbose_name='性别')
    def __str__(self):
        return self.TeaNum
    class Meta:
        verbose_name = '教师信息'
        verbose_name_plural = '教师信息'

class shenq(models.Model):
    # models=Stuinfo
    num = models.AutoField(primary_key=True,verbose_name='预编码号')
    Stunum=models.ForeignKey(Stuinfo,on_delete=models.CASCADE,verbose_name='学号')
    time=models.DateTimeField(verbose_name='申请时间',auto_now=True)
    edu = models.IntegerField(default=10000, verbose_name='贷款额度')
    status=models.IntegerField(default=0,verbose_name='审批状态')
    def __str__(self):
        return str(self.num)
    class Meta:
        verbose_name = '贷款申请信息'
        verbose_name_plural = '贷款申请信息'

class daikuan(models.Model):
    num=models.OneToOneField(shenq,verbose_name='预编码号',on_delete=models.CASCADE)
    id=models.AutoField(primary_key=True,verbose_name='编码号')
    TeaNum=models.ForeignKey(Teacher,on_delete=models.CASCADE,verbose_name='职工号')
    time=models.DateTimeField(verbose_name='审批时间',auto_now=True)
    status = models.IntegerField(default=0, verbose_name='还款状态')
    need = models.IntegerField(default=0,verbose_name='所需还款')
    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name = '贷款信息'
        verbose_name_plural = '贷款信息'


class Register(models.Model):
   username = models.CharField(max_length = 32,verbose_name = '学号',)
   password = models.CharField(max_length = 32,verbose_name = '密码',default='jianghuai')
   name=models.CharField(max_length=20,verbose_name='姓名',default='')
   email = models.EmailField(verbose_name = '注册邮箱',blank=True,help_text='可不填')
   phone_number = models.CharField(max_length = 14,verbose_name = '电话号码',blank=True)
   class Meta:
       verbose_name_plural='账号管理'
       verbose_name='账号管理'

django/daikuan/app/templates/app/common/daikuaninfo.html
{% extends 'app/base/base_stu.html' %}
{% load staticfiles %}
{% block xinxi %}

<li><a>欢迎{{ stu.StuName }}同学</a></li><li><a href="{% url 'app:logout' %}">注销</a></li>


{% endblock %}
{% block title %}贷款信息{% endblock %}
{% block detail %}
     <h1 style="text-align: center">您的贷款信息如下</h1>
    <div class="caidan right">
            <table class="table">
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">真实姓名</td><td colspan="2"><output    name="StuName"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.num.Stunum.StuName }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学号</td><td colspan="2"><output    name="StuNum"  style="line-height: 25px;border: none;outline:none"  >{{ daikuan.num.Stunum.StuNum }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">性别</td><td colspan="2"><output class="myforms-3-2"  style="line-height: 25px;border: none;outline:none"  name="Sex" >{{ daikuan.num.Stunum.get_Sex_display }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">联系方式</td><td ><output   name="Tel" style="line-height: 25px;border: none;outline:none"   >{{ daikuan.num.Stunum.Tel }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">院系</td><td colspan="2"><output    name="department"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.num.Stunum.get_department_display }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">专业</td><td colspan="2"><output    name="major"  style="line-height: 25px;border: none;outline:none"  >{{ daikuan.num.Stunum.major }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">身份证</td><td colspan="2"><output    name="stuid"  style="line-height: 25px;border: none;outline:none"  >{{ daikuan.num.Stunum.stuid }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">常用邮箱</td><td colspan="2"><output    name="email"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.num.Stunum.email }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">申请时间</td><td colspan="2"><output    name="email"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.num.time }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">申请额度</td><td colspan="2"><output    name="email"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.num.edu }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">审批时间</td><td colspan="2"><output    name="email"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.time }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">审批人</td><td colspan="2"><output    name="email"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.TeaNum.TeaName }}</output></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">审批人联系方式</td><td colspan="2"><output    name="phone"  style="line-height: 25px;border: none;outline:none" >{{ daikuan.TeaNum.Tel }}</output></td></tr>


                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">应还贷款</td><td ><output   name="edu" style="line-height: 25px;border: none;outline:none"    ></output>
                    {% if daikuan.need %}
                        {{ daikuan.need }}
                    {% else %}
                        <p id="moneyneed"></p>
                    {% endif %}</td></tr>

                
            </tbody>
        </table>
    </div>
    <script>
    date= new Date()
    oldyear={{ daik.time.year }}
    year=date.getFullYear()
    oldmonth={{ daik.time.month }}
    Month=date.getMonth()+1
    money=((year-oldyear)*12+Month-oldmonth)*{{ daik.num.edu }}*0.05+{{ daik.num.edu }};
    document.getElementById('moneyneed').innerHTML=money</script>
{% endblock %}

django/daikuan/app/templates/app/common/daikuaninfo2.html
{% extends 'app/base/base_tea.html' %}
{% load staticfiles %}
{% block title %}贷款信息{% endblock %}
{% block detail %}
    <h1 style="text-align: center">所有贷款信息如下</h1>
    <div class="caidan right">
    <table class="stuinfo">
            <tr><th>学号</th><th>申请时间</th><th>额度</th><th>审批时间</th><th>详情链接</th></tr>
        {% for i in page %}
            <tr><td>{{i.num.Stunum.StuNum}}</td><td>{{ i.num.time }}</td><td>{{ i.num.edu }}</td><td>{{ i.time}}</td><td><a class="nosolid" href="{% url 'app:dkdetail' i.num.Stunum %}" >click</a></td></tr>
        {% endfor %}
    </table>
    <div class="page">
        {% if page.has_previous %}
            <a href="{% url 'app:allinfo' page.previous_page_number %}">上一页</a>
        {% endif %}
            <span class="current">第{{ page.number }}页/共{{ page.paginator.num_pages }}页 </span>
        {% if page.has_next %}
            <a href="{% url 'app:allinfo' page.next_page_number %}">下一页</a>
        {% endif %}

    </div>
    </div>
{% endblock %}

django/daikuan/app/templates/app/common/index.html
{#login/templates/login/index.html#}
{% extends 'app/base/base.html' %}
{% load staticfiles %}
{% load static %}

{% block image %}<img src="{% static 'images/背景图.jpg' %}" width=100% height=550px>{% endblock %}

django/daikuan/app/templates/app/common/login.html
{% extends 'app/base/base.html' %}
{% load staticfiles %}
{%  load static %}
{% block title %}登录{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'css/login.css' %}">{% endblock %}
{% block xinxi %}{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-login' action="{% url 'app:index' %}" method="post">
              {% csrf_token %}
              <img src="{% static 'images/logo_school.png' %}">
              <h2 class="text-center">欢迎登录</h2>
              <div class="form-group">
                <label for="id_username">用户名：</label>
                <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
              </div>
              <div class="form-group">
                <label for="id_password">密码：</label>
                <input type="password" name='password' class="form-control" id="id_password" placeholder="Password" required>
              </div>
              <span style="color:red;">{{ error_msg }}</span>
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">登录</button>
          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}