django/daikuan/app/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import admin
from . import views
# from django.contrib.auth import views as auth_views
app_name='app'
urlpatterns = [
    url(r'^submit$',views.submit,name='submit'),
    url(r'^shouye$',views.shouye,name='shouye'),
    url(r'^index$', views.index,name='index'),
    url(r'^daikuaninfo$',views.daikuaninfo,name='daikuaninfo'),
    url(r'^alldaikuaninfo/(\d*)$',views.daikuaninfo2,name='daik2'),
    url(r'^stuinfo$',views.stuinfo,name='stuinfo'),
    url('^daikuanshenq$',views.daikuanshenq,name='daikuanshenq'),
    url(r'^login$', views.login,name='login'),
    url(r'^logout$', views.logout,name='logout'),
    url(r'^teainfo$',views.teainfo,name='teainfo'),
    url(r'^daikuanshenp/(\d*)$',views.daikuanshenp,name='daikuanshenp'),
    url(r'^upload$',views.upload,name='upload'),
    url(r'^change$',views.change,name='change'),
    url(r'^allstuinfo/(\d*)$',views.allinfo,name='allinfo'),
    url(r'^detail/([A-Z]{2}\d{6})$',views.detail,name='detail'),
    url(r'^shenh/(.*)$',views.shenh,name='shenh'),
    url(r'^daikuandetail/([A-Z]{2}\d{6})$',views.daikuandetail,name='dkdetail'),
    url(r'^tuihui/([A-Z]{2}\d{6})$',views.tuihui,name='tuihui'),
    url(r'^huankuan/([A-Z]{2}\d{6})$',views.huankuan,name='huankuan'),
    url(r'^daikuanshenq2$',views.daikuanshenq2,name='daikuanshenq2'),
    url(r'^addadm$',views.admm,name='addadm'),
    url(r'^deladm$',views.admm2,name='deladm'),
]

django/daikuan/daikuan/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),

]

django/daikuan/app/models.py
from django.db import models

# Create your models here.
class Stuinfo(models.Model):
    StuNum=models.CharField(max_length=8,primary_key=True,verbose_name='学号')
    StuName=models.CharField(max_length=20,verbose_name='姓名')
    Sex=models.CharField(max_length=2,choices=(('W','女'),('M','男')),verbose_name='性别')
    department=models.CharField(max_length=20,choices=(('L','理工部'),('W','文艺部'),('G','管理部'),('J','经济系')),verbose_name='系别')
    stuid=models.CharField(max_length=18,verbose_name='身份证')
    Tel=models.CharField(max_length=12,verbose_name='电话')
    major=models.CharField(verbose_name='专业',max_length=20)
    email=models.EmailField(verbose_name='邮箱',blank=True,help_text='可不填')
    def __str__(self):
        return self.StuNum
    class Meta:
        verbose_name='学生信息'
        verbose_name_plural='学生信息'

class Teacher(models.Model):
    TeaNum=models.CharField(max_length=8,primary_key=True,verbose_name='职工号')
    TeaName=models.CharField(max_length=20,verbose_name='姓名')
    Tel=models.CharField(max_length=12,verbose_name='电话')
    sex = models.CharField(max_length=2,choices=(('W', '女'), ('M', '男')), verbose_name='性别')
    def __str__(self):
        return self.TeaNum
    class Meta:
        verbose_name = '教师信息'
        verbose_name_plural = '教师信息'

class shenq(models.Model):
    # models=Stuinfo
    num = models.AutoField(primary_key=True,verbose_name='预编码号')
    Stunum=models.ForeignKey(Stuinfo,on_delete=models.CASCADE,verbose_name='学号')
    time=models.DateTimeField(verbose_name='申请时间',auto_now=True)
    edu = models.IntegerField(default=10000, verbose_name='贷款额度')
    status=models.IntegerField(default=0,verbose_name='审批状态')
    def __str__(self):
        return str(self.num)
    class Meta:
        verbose_name = '贷款申请信息'
        verbose_name_plural = '贷款申请信息'

class daikuan(models.Model):
    num=models.OneToOneField(shenq,verbose_name='预编码号',on_delete=models.CASCADE)
    id=models.AutoField(primary_key=True,verbose_name='编码号')
    TeaNum=models.ForeignKey(Teacher,on_delete=models.CASCADE,verbose_name='职工号')
    time=models.DateTimeField(verbose_name='审批时间',auto_now=True)
    status = models.IntegerField(default=0, verbose_name='还款状态')
    need = models.IntegerField(default=0,verbose_name='所需还款')
    def __str__(self):
        return str(self.id)
    class Meta:
        verbose_name = '贷款信息'
        verbose_name_plural = '贷款信息'


class Register(models.Model):
   username = models.CharField(max_length = 32,verbose_name = '学号',)
   password = models.CharField(max_length = 32,verbose_name = '密码',default='jianghuai')
   name=models.CharField(max_length=20,verbose_name='姓名',default='')
   email = models.EmailField(verbose_name = '注册邮箱',blank=True,help_text='可不填')
   phone_number = models.CharField(max_length = 14,verbose_name = '电话号码',blank=True)
   class Meta:
       verbose_name_plural='账号管理'
       verbose_name='账号管理'

django/daikuan/app/templates/app/student/daikuanshenq.html
{% extends 'app/student/stuinfo.html' %}
{% block title %}贷款申请{% endblock %}
{% block detail %}
    <div class="caidan right">
    <form id="register" action="{% url 'app:submit' %}" method="post" >
    <table class="table">
        {% csrf_token%}
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">真实姓名</td><td colspan="2"><input    name="StuName" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入您的名字" required value="{{ stu.StuName }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学号</td><td colspan="2"><input    name="StuNum" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入学号" required value="{{ stu.StuNum }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">性别</td><td colspan="2"><input class="myforms-3-2" type="text" style="line-height: 25px;border: none;outline:none" checked ="checked" name="Sex" value="{{ stu.get_Sex_display }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">联系方式</td><td ><input   name="Tel" style="line-height: 25px;border: none;outline:none" type="tel" minlength="11" maxlength="11" placeholder="请输入手机" required value="{{ stu.Tel }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">院系</td><td colspan="2"><input    name="department" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入院系" required value="{{ stu.get_department_display }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">专业</td><td colspan="2"><input    name="major" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入专业" required value="{{ stu.major }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">身份证</td><td colspan="2"><input    name="stuid" type="text" style="line-height: 25px;border: none;outline:none" placeholder="身份证" required value="{{ stu.stuid }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">常用邮箱</td><td colspan="2"><input    name="email" type="email" style="line-height: 25px;border: none;outline:none" placeholder="请输入邮箱(可不填)"  value="{{ stu.email }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">申请额度</td><td colspan="2"><input    name="edu" type="number" style=" -webkit-appearance: none !important; line-height: 25px;border: none;outline:none" placeholder="请输入要申请的额度"  required ></td></tr>
            </tbody>
    </table>
    <button class="btn btn-success" type="submit" style="margin: 0 20% 0 20%;width: 60%" οnclick="registerid_submit()">提交</button>
    <p><font color="red">注意：在驳回或审批前不可再提交</font></p>
    </form>
    </div>
{% endblock %}

django/daikuan/app/templates/app/student/stuinfo.html
{% extends 'app/base/base_stu.html' %}
{% load staticfiles %}

{% block title %}学生信息{% endblock %}
{% block detail %}
    <h1 style="text-align: center">您的个人信息如下</h1>
    <div class="caidan right">
         <form id="register" action="{% url 'app:change' %}" method="post" >
            <table class="table">
                {% csrf_token %}
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">真实姓名</td><td colspan="2"><input    name="StuName" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入您的名字" required value="{{ stu.StuName }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学号</td><td colspan="2"><input    name="StuNum" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入学号" required value="{{ stu.StuNum }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">性别</td><td colspan="2"><input class="myforms-3-2" type="text" style="line-height: 25px;border: none;outline:none" checked ="checked" name="Sex" value="{{ stu.get_Sex_display }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">联系方式</td><td ><input   name="Tel" style="line-height: 25px;border: none;outline:none" type="tel" minlength="11" maxlength="11" placeholder="请输入手机" required value="{{ stu.Tel }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">院系</td><td colspan="2"><input    name="department" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入院系" required value="{{ stu.get_department_display }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">专业</td><td colspan="2"><input    name="major" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入专业" required value="{{ stu.major }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">身份证</td><td colspan="2"><input    name="stuid" type="text" style="line-height: 25px;border: none;outline:none" placeholder="身份证" required value="{{ stu.stuid }}"></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">常用邮箱</td><td colspan="2"><input    name="email" type="email" style="line-height: 25px;border: none;outline:none" placeholder="请输入邮箱"  value="{{ stu.email }}"></td></tr>
            </tbody>
        </table>
        <button class="btn btn-success" type="submit" style="margin: 0 20% 0 20%;width: 60%" οnclick="registerid_submit()">修改</button>
         </form>
    </div>
{% endblock %}

django/daikuan/app/templates/app/student/upload.html
{% extends 'app/base/base_stu.html' %}
{% load staticfiles %}
{% block title %}完善学生信息{% endblock %}
{% block detail %}
    <div class="caidan right">
         <form id="register" action="" method="post" >
             {% csrf_token %}
            <table class="table">
                <tbody>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">真实姓名</td><td colspan="2"><input    name="StuName" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入您的名字" required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">学号</td><td colspan="2"><input    name="StuNum" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入学号" value="{{ name.username }}" required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">性别</td><td colspan="2"><input class="myforms-3-2" type="radio" checked ="checked" name="Sex" value="M">男<input class="myforms-3-3" type="radio"  name="Sex" value="W">女</td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">联系方式</td><td ><input   name="Tel" style="line-height: 25px;border: none;outline:none" type="tel" minlength="11" maxlength="11" placeholder="请输入手机" required></td><td></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">院系</td><td colspan="2"><input    name="department" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入院系" required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">专业</td><td colspan="2"><input    name="major" type="text" style="line-height: 25px;border: none;outline:none" placeholder="请输入专业" required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">身份证</td><td colspan="2"><input    name="stuid" type="text" style="line-height: 25px;border: none;outline:none" placeholder="身份证" required></td></tr>
                <tr><td  style="line-height: 25px;word-break: keep-all;white-space: nowrap;text-overflow: ellipsis;">常用邮箱</td><td colspan="2"><input    name="email" type="email" style="line-height: 25px;border: none;outline:none" placeholder="请输入邮箱" ></td></tr>
            </tbody>
        </table>
        <button class="btn btn-success" type="submit" style="margin: 0 20% 0 20%;width: 60%" οnclick="registerid_submit()">提交</button>
         </form>
    </div>
{% endblock %}